name: Testing Laravel
on:
  workflow_dispatch:
  push:
jobs:
  laravel:
    name: Laravel (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest

    # Docs: https://docs.github.com/en/actions/using-containerized-services
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: secret
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.0']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Docs: https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, dom, fileinfo, mysql
          coverage: pcov

      - name: Install Composer dependencies
        run: |
          composer install --prefer-dist --no-scripts --ignore-platform-reqs --no-autoloader --no-interaction
          composer dump-autoload --optimize

      - name: Prepare the application
        run: |
          php -r "file_exists('.env') || copy('.env.ci', '.env');"
          php artisan key:generate
      - name: Artisan commands
        run: php artisan config:clear

      - name: Run Migration and install passport
        run: |
          php artisan migrate -v --force
          php artisan passport:install
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}

      - name: Prepare tests
        run: |
          cp phpunit.xml phpunit.xml.bkp
          cp phpunit.xml.dev phpunit.xml

      - name: Test with phpunit
        run: timeout 1200 php artisan test --coverage-clover=coverage.xml
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
